"""init_core_v6

Revision ID: 1813409f56ea
Revises: 0001_init
Create Date: 2026-02-11 18:18:30.483025
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1813409f56ea'
down_revision = '0001_init'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('actor', sa.String(length=64), nullable=False))
    op.add_column('audit_logs', sa.Column('entity', sa.String(length=32), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'user_id')
    op.add_column('transactions', sa.Column('from_address', sa.String(length=128), nullable=False))
    op.add_column('transactions', sa.Column('to_address', sa.String(length=128), nullable=False))
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('transactions', 'block_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('transactions', 'prev_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('transactions', 'block_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_transactions_block_index'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_receiver'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_sender'), table_name='transactions')
    op.drop_constraint(op.f('transactions_block_hash_key'), 'transactions', type_='unique')
    op.drop_constraint(op.f('transactions_tx_hash_key'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_block_hash'), 'transactions', ['block_hash'], unique=True)
    op.create_index(op.f('ix_transactions_block_index'), 'transactions', ['block_index'], unique=False)
    op.create_index(op.f('ix_transactions_from_address'), 'transactions', ['from_address'], unique=False)
    op.create_index(op.f('ix_transactions_to_address'), 'transactions', ['to_address'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'tx_hash')
    op.drop_column('transactions', 'sender_id')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               nullable=False,
               existing_server_default=sa.text('1000.00'))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('1000.00'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('tx_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_to_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_index'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_hash'), table_name='transactions')
    op.create_unique_constraint(op.f('transactions_tx_hash_key'), 'transactions', ['tx_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('transactions_block_hash_key'), 'transactions', ['block_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_transactions_sender'), 'transactions', ['sender_id'], unique=False)
    op.create_index(op.f('idx_transactions_receiver'), 'transactions', ['receiver_id'], unique=False)
    op.create_index(op.f('idx_transactions_block_index'), 'transactions', ['block_index'], unique=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'block_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transactions', 'prev_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transactions', 'block_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'to_address')
    op.drop_column('transactions', 'from_address')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'meta')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'actor')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
